### ISSUE TITLE
Can't connect on ollama

### ISSUE THREAD

**Issue by electroheadfx** [jakobhoeg/nextjs-ollama-llm-ui#52]
Great app with next and shadcn-ui :)

I test on Macos 14.5,  The app can't connect on port 11434
I tested ollama on this port : `http://localhost:11434` it works
My env is setup to `NEXT_PUBLIC_OLLAMA_URL="http://localhost:11434"`

```bash
 - Local:        http://localhost:3000
  - Environments: .env

 ✓ Starting...
 ✓ Ready in 1759ms
 ○ Compiling / ...
 ✓ Compiled / in 2.9s (3382 modules)
 GET / 200 in 3188ms
 ✓ Compiled in 359ms (1678 modules)
 ✓ Compiled /api/tags in 395ms (1708 modules)
 ⨯ TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11372:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GET (webpack-internal:///(rsc)/./src/app/api/tags/route.ts:9:17)
    at async /Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53446
    at async e_.execute (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44747)
    at async e_.handle (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54700)
    at async doRender (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1377:42)
    at async cacheEntry.responseCache.get.routeKind (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1599:28)
    at async DevServer.renderToResponseWithComponentsImpl (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1507:28)
    at async DevServer.renderPageComponent (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1924:24)
    at async DevServer.renderToResponseImpl (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:1962:32)
    at async DevServer.pipeImpl (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallRenderRequest (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/next-server.js:272:17)
    at async DevServer.handleRequestImpl (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async /Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Volumes/T7/work/ai/nextjs-ollama-llm-ui/node_modules/.pnpm/next@14.2.3_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13) {
  cause: Error: connect ECONNREFUSED ::1:11434
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 11434
  }
}
 GET /api/tags 500 in 442ms
 ⨯ TypeError: fetch failed

```

**Comment by malteneuss** [comment]
Could you check if ollama is indeed working, e.g. with

```shell
curl http://localhost:11434/api/tags
```

**Comment by electroheadfx** [comment]
hey, thanks, yes ollama seem working fine:
```json
curl http://localhost:11434/api/tags
{"models":[{"name":"deepseek-coder:33b","model":"deepseek-coder:33b","modified_at":"2024-05-26T08:49:40.935144754+02:00","size":18819456424,"digest":"acec7c0b0fd9ad4c9e82620b32dcb794120d40623ab53d5e1453a948d7d204d8","details":{"parent_model":"","format":"gguf","family":"llama","families":["llama"],"parameter_size":"33B","quantization_level":"Q4_0"},"expires_at":"0001-01-01T00:00:00Z"},{"name":"codeqwen:latest","model":"codeqwen:latest","modified_at":"2024-05-25T19:02:11.583984379+02:00","size":4179444931,"digest":"a6f7662764bd788851a043972852b42414e047ea5042ec733c5fafef77fb267a","details":{"parent_model":"","format":"gguf","family":"qwen2","families":["qwen2"],"parameter_size":"7B","quantization_level":"Q4_0"},"expires_at":"0001-01-01T00:00:00Z"}]}%
```

**Comment by malteneuss** [comment]
My remaining suggestions are to try `NEXT_PUBLIC_OLLAMA_URL="http://127.0.0.01:11434"` without a DNS name. If that doesn't work,  try `npm run build` to build a standalone artefact and then run that artefact with`node .next/standalone/server.js` (or index.js). And if that doesn't work, i would ask in the nextjs project ^^

**Comment by electroheadfx** [comment]
Hey, it works with 127.0.0.01 !
thanks
