### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by karrarkazuya** [jakobhoeg/nextjs-ollama-llm-ui#84]
a fresh install on a fresh server following the steps provided.
this error throws on 
npm run dev

```
root@myserver:/usr/share/nginx/html/nextjs-ollama-llm-ui# npm run dev

> nextjs-ollama-local-ai@0.1.0 dev
> next dev

/usr/share/nginx/html/nextjs-ollama-llm-ui/node_modules/next/dist/compiled/commander/index.js:1
(()=>{var t={81:t=>{"use strict";t.exports=require("child_process")},361:t=>{"use strict";t.exports=require("events")},147:t=>{"use strict";t.exports=require("fs")},17:t=>{"use strict";t.exports=require("path")},282:t=>{"use strict";t.exports=require("process")},161:(t,e,i)=>{const{InvalidArgumentError:n}=i(854);class Argument{constructor(t,e){this.description=e||"";this.variadic=false;this.parseArg=undefined;this.defaultValue=undefined;this.defaultValueDescription=undefined;this.argChoices=undefined;switch(t[0]){case"<":this.required=true;this._name=t.slice(1,-1);break;case"[":this.r
[
alot of minified code here
]

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at Module.mod.require (/usr/share/nginx/html/nextjs-ollama-llm-ui/node_modules/next/dist/server/require-hook.js:65:28)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/usr/share/nginx/html/nextjs-ollama-llm-ui/node_modules/next/dist/bin/next:7:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by jakobhoeg** [comment]
Hi, @karrarkazuya.

Which version of Node.js do you have on your server?

**Comment by MacOSIcons** [comment]
DO NOT USE APT TO INSTALL NODEJS. USE NVM TO INSTALL LTS.
